[system]
compatible=qemuarm64
bootloader=uboot
data-directory=/data

[keyring]
path=/etc/aegis/ca.cert.pem

[slot.rootfs.0]
device=/dev/disk/by-label/ROOTFS_A
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-label/ROOTFS_B
type=ext4
bootname=B
